name: Markdown Check

on:
  push:
    branches: [main]

jobs:
  check-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Check README exists
        run: |
          test -f README.md
          echo "README.md exists."
